name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend_flask:
    name: Backend (Flask)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lint Python code
      - name: Lint Python code
        run: |
          if [ -f .flake8 ] || [ -f setup.cfg ] || [ -f tox.ini ] || [ -f .pep8 ]; then
            flake8 .
          else
            echo "No lint configuration found, skipping linting."
          fi

      # Run Python tests
      - name: Run Python tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest
          else
            echo "No tests found, skipping tests."
          fi

  deploy:
    name: Deploy & Push to Docker Hub
    needs: [backend_flask]
    runs-on: ubuntu-latest
    environment: PROD # Fixed typo here

    steps:
      - uses: actions/checkout@v3

      # List repository files for debugging
      - name: List repository files
        run: ls -al

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend_flask:latest .

      # Log in to Docker Hub securely
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend_flask:latest
